### ISSUE TITLE
getting package invalid error when trying to add extention

### ISSUE THREAD

**Issue by bluexbyte** [TanaTanoi/messenger_formatter#9]
![error](https://cloud.githubusercontent.com/assets/13504077/14454197/4a08e254-00ed-11e6-9b4f-ae120d745f0d.png)

i have no idea how chrome extentions work but chrome is Version 46.0.2490.86 (64-bit)

**Comment by TanaTanoi** [comment]
I'm not sure tbh lol, but you're 3 whole versions behind (idk if that would affect it?) Let me know if updating chrome works :)
